=== cloud-emoticon/store-repos/schema/RepositoryMetadata.json
{
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "location": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": [
                        "localJson",
                        "localXml",
                        "remoteJson"
                    ],
                    "type": "string"
                },
                "remoteUrl": {
                    "type": "string"
                }
            },
            "required": [
                "type"
            ]
        },
        "description": {
            "type": "string"
        },
        "author": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "avatarUrl": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        }
    },
    "required": [
        "author",
        "description",
        "location",
        "name"
    ],
    "$schema": "http://json-schema.org/draft-07/schema#"
}

=== cloud-emoticon/store-repos/kt-favorites.meta.json
{
    "$schema": "https://github.com/cloud-emoticon/store-repos/raw/master/schema/RepositoryMetadata.json",
    "name": "KT's favorites",
    "location": {
        "type": "localJson"
    },
    "description": "KT's favorites. What comes default by Cloud Emoticon 1 for Android.",
    "author": {
        "name": "KTachibanaM",
        "url": "https://twitter.com/KTachibana_M",
        "avatarUrl": "https://raw.githubusercontent.com/cloud-emoticon/store-repos/master/avatars/KTachibana_M.jpg"
    }
}

=== cloud-emoticon/store-repos/midori.meta.json
{
    "$schema": "https://github.com/cloud-emoticon/store-repos/raw/master/schema/RepositoryMetadata.json",
    "name": "Midori",
    "location": {
        "type": "localXml"
    },
    "description": "Midori",
    "author": {
        "name": "Midori Yakumo",
        "url": "https://twitter.com/MidoriYakumo",
        "avatarUrl": "https://raw.githubusercontent.com/cloud-emoticon/store-repos/master/avatars/Midori Yakumo.png"
    }
}

=== cloud-emoticon/store-repos/oliver-wang.meta.json
{
    "$schema": "https://github.com/cloud-emoticon/store-repos/raw/master/schema/RepositoryMetadata.json",
    "name": "Oliver Wang",
    "location": {
        "type": "localXml"
    },
    "description": "Oliver Wang",
    "author": {
        "name": "Oliver Wang",
        "url": "https://twitter.com/Toohashi",
        "avatarUrl": "https://raw.githubusercontent.com/cloud-emoticon/store-repos/master/avatars/Oliver Wang.jpg"
    }
}

=== cloud-emoticon/store-repos/yashi-poi.meta.json
{
    "$schema": "https://github.com/cloud-emoticon/store-repos/raw/master/schema/RepositoryMetadata.json",
    "name": "Yashi-poi",
    "location": {
        "type": "localXml"
    },
    "description": "Yashi-poi. What comes default by Cloud Emoticon 1 for iOS.",
    "author": {
        "name": "神楽坂雅詩",
        "url": "https://twitter.com/kagurazakayashi",
        "avatarUrl": "https://raw.githubusercontent.com/cloud-emoticon/store-repos/master/avatars/神楽坂雅詩.png"
    }
}

=== cloud-emoticon/store-repos/japaneseemoticons.meta.json
{
    "$schema": "https://github.com/cloud-emoticon/store-repos/raw/master/schema/RepositoryMetadata.json",
    "name": "japaneseemoticons.net",
    "location": {
        "type": "localXml"
    },
    "description": "japaneseemoticons.net transformed by wicast",
    "author": {
        "name": "wicast chen",
        "url": "https://twitter.com/wicastchen",
        "avatarUrl": "https://raw.githubusercontent.com/cloud-emoticon/store-repos/master/avatars/wicast chen.jpg"
    }
}

=== cloud-emoticon/store-repos/a-land.meta.json
{
    "$schema": "https://github.com/cloud-emoticon/store-repos/raw/master/schema/RepositoryMetadata.json",
    "name": "A岛颜文字汇集",
    "location": {
        "type": "localXml"
    },
    "description": "A岛颜文字汇集",
    "author": {
        "name": "陈少举",
        "url": "https://twitter.com/chenshaoju",
        "avatarUrl": "https://raw.githubusercontent.com/cloud-emoticon/store-repos/master/avatars/陈少举.jpg"
    }
}

=== cloud-emoticon/store-repos/remote-demo.meta.json
{
    "$schema": "https://github.com/cloud-emoticon/store-repos/raw/master/schema/RepositoryMetadata.json",
    "name": "Remote repo demo",
    "location": {
        "type": "remoteJson",
        "remoteUrl": "http://www.ktachibana.party/cloudemoticon/remote-demo.json"
    },
    "description": "A demo to show how to host a repo not on https://github.com/cloud-emoticon/store-repos\nIt will still have the same content as 'KT's favorites'",
    "author": {
        "name": "KTachibanaM",
        "url": "https://twitter.com/KTachibana_M",
        "avatarUrl": "https://raw.githubusercontent.com/cloud-emoticon/store-repos/master/avatars/KTachibana_M.jpg"
    }
}

=== cloud-emoticon/store-repos/kt-cia.meta.json
{
    "$schema": "https://github.com/cloud-emoticon/store-repos/raw/master/schema/RepositoryMetadata.json",
    "name": "CIA",
    "location": {
        "type": "localJson"
    },
    "description": "What the CIA uses",
    "author": {
        "name": "KTachibanaM",
        "url": "https://twitter.com/KTachibana_M",
        "avatarUrl": "https://raw.githubusercontent.com/cloud-emoticon/store-repos/master/avatars/KTachibana_M.jpg"
    }
}
