=== cloud-emoticon/store-repos/schema/RepositoryMetadata.json
{
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "location": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": [
                        "localJson",
                        "localXml",
                        "remoteJson"
                    ],
                    "type": "string"
                },
                "remoteUrl": {
                    "type": "string"
                }
            },
            "required": [
                "type"
            ]
        },
        "description": {
            "type": "string"
        },
        "author": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "avatarUrl": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        }
    },
    "required": [
        "author",
        "description",
        "location",
        "name"
    ],
    "$schema": "http://json-schema.org/draft-07/schema#"
}

=== cloud-emoticon/store-repos/kaomojiya.meta.json
{
    "$schema": "https://github.com/cloud-emoticon/store-repos/raw/master/schema/RepositoryMetadata.json",
    "name": "颜文字屋",
    "location": {
        "type": "localXml"
    },
    "description": "kaomojiya.com transformed by wicast",
    "author": {
        "name": "wicast chen",
        "url": "https://twitter.com/wicastchen",
        "avatarUrl": "https://raw.githubusercontent.com/cloud-emoticon/store-repos/master/avatars/wicast chen.jpg"
    }
}
